SELECT CASE WHEN ZPUSHNAME IS NULL THEN 'Name not available' ELSE ZPUSHNAME END AS Name,
       SUBSTRING(ZWABLACKLISTITEM.ZJID, 1, 12) AS PhoneNumber
FROM ZWABLACKLISTITEM
LEFT JOIN ZWAPROFILEPUSHNAME ON ZWABLACKLISTITEM.ZJID = ZWAPROFILEPUSHNAME.ZJID
