SELECT ZWACHATSESSION.ZPARTNERNAME AS Contact,
       ZWAPROFILEPUSHNAME.ZPUSHNAME AS UserName,
       SUBSTRING(ZJID, 1, 12) AS PhoneNumber,
       (SELECT COUNT(*) FROM ZWAMESSAGE
         WHERE ZWACHATSESSION.ZSESSIONTYPE == 0
           AND ZMESSAGETYPE IN ('0','1','2','3','4','5','7','8','11','14','15','38','39')
           AND (ZFROMJID = ZWAPROFILEPUSHNAME.ZJID OR ZTOJID = ZWAPROFILEPUSHNAME.ZJID)
       ) AS NumberOfMessages,
       datetime(ZWAMESSAGE.ZMESSAGEDATE + 978307200, 'unixepoch') AS MessageDate
FROM ZWACHATSESSION
LEFT JOIN ZWAMESSAGE ON ZWACHATSESSION.ZLASTMESSAGE = ZWAMESSAGE.Z_PK
LEFT JOIN ZWAPROFILEPUSHNAME ON ZWACHATSESSION.ZCONTACTJID = ZWAPROFILEPUSHNAME.ZJID
WHERE ZWACHATSESSION.ZSESSIONTYPE == 0 AND ZJID IS NOT NULL
GROUP BY ZWACHATSESSION.ZPARTNERNAME
HAVING MAX(datetime(ZWAMESSAGE.ZMESSAGEDATE + 978307200, 'unixepoch')) AND NumberOfMessages > 0
ORDER BY CASE WHEN ZWACHATSESSION.ZPARTNERNAME LIKE '+%' THEN 1 ELSE 0 END ASC,
         ZWACHATSESSION.ZPARTNERNAME
