SELECT CASE WHEN ZWAMESSAGE.ZGROUPMEMBER IS NOT NULL THEN SUBSTRING(ZWAGROUPMEMBER.ZMEMBERJID, 1, 12)
            WHEN ZWAMESSAGE.ZFROMJID IS NULL THEN 'Database owner'
            ELSE SUBSTRING(ZWAMESSAGE.ZFROMJID, 1, 12) END AS Sender,
       CASE WHEN ZWAMESSAGE.ZTOJID IS NULL AND ZWAMESSAGE.ZGROUPMEMBER IS NULL THEN 'Database owner'
            WHEN ZWAMESSAGE.ZTOJID IS NULL AND ZWAMESSAGE.ZGROUPMEMBER IS NOT NULL THEN ZWACHATSESSION.ZPARTNERNAME
            ELSE SUBSTRING(ZWAMESSAGE.ZTOJID, 1, 12) END AS Receiver,
       datetime(ZWAMESSAGE.ZMESSAGEDATE + 978307200, 'unixepoch') AS MessageDate,
       ZLATITUDE AS Latitude,
       ZLONGITUDE AS Longitude
FROM ZWAMESSAGE
JOIN ZWACHATSESSION ON ZWACHATSESSION.Z_PK = ZWAMESSAGE.ZCHATSESSION
LEFT JOIN ZWAMEDIAITEM ON ZWAMESSAGE.ZMEDIAITEM = ZWAMEDIAITEM.Z_PK
LEFT JOIN ZWAGROUPMEMBER ON ZWAMESSAGE.ZGROUPMEMBER = ZWAGROUPMEMBER.Z_PK
WHERE ZWAMESSAGE.ZMESSAGETYPE = 5
ORDER BY MessageDate
