SELECT ZPARTNERNAME AS Group_Name,
       datetime(ZWAMESSAGE.ZMESSAGEDATE + 978307200, 'unixepoch') AS Message_Date,
       (SELECT COUNT(*) FROM ZWAMESSAGE
         WHERE ZWAMESSAGE.ZMESSAGETYPE IN ('0','1','38','2','39','3','4','5','7','8','11','14','15','46')
           AND (ZWAMESSAGE.ZTOJID = ZWACHATSESSION.ZCONTACTJID OR ZWAMESSAGE.ZFROMJID = ZWACHATSESSION.ZCONTACTJID)
       ) AS Number_of_Messages,
       ZWACHATPUSHCONFIG.ZMUTEDUNTIL AS Is_muted
FROM ZWAMESSAGE
LEFT JOIN ZWACHATSESSION ON ZWACHATSESSION.ZLASTMESSAGE = ZWAMESSAGE.Z_PK
LEFT JOIN ZWAPROFILEPUSHNAME ON ZWACHATSESSION.ZCONTACTJID = ZWAPROFILEPUSHNAME.ZJID
LEFT JOIN ZWACHATPUSHCONFIG ON ZWACHATPUSHCONFIG.ZJID = ZWACHATSESSION.ZCONTACTJID
WHERE ZSESSIONTYPE = 1
ORDER BY ZWACHATSESSION.ZPARTNERNAME ASC
