apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fw.fullname" . }}
  labels:
    {{- include "fw.labels" . | nindent 4 }}
type: Opaque
stringData:
  FW_DATABASE_URL: {{ include "fw.databaseUrl" . | quote }}
  FW_BROKER_URL: {{ include "fw.brokerUrl" . | quote }}
  kedaBrokerHost: {{ include "fw.brokerKedaHost" . | quote }}
  {{- if include "fw.s3Enabled" . }}
  FW_S3_ACCESS_KEY: {{ include "fw.s3AccessKey" . | quote }}
  FW_S3_SECRET_KEY: {{ include "fw.s3SecretKey" . | quote }}
  {{- end }}
  {{- range $name, $value := .Values.analyzerSecrets }}
  {{ $name }}: {{ $value | quote }}
  {{- end }}
