"""Parameterized SQL for iOS ``ChatStorage.sqlite``.

All user-supplied values are bound as named parameters — never interpolated.
These queries target the current known schema generation; they will move into
the versioned schema registry (see docs/ARCHITECTURE.md §4) in a later phase.
"""

CHAT_LIST = """
SELECT ZWACHATSESSION.ZPARTNERNAME AS Contact,
       ZWAPROFILEPUSHNAME.ZPUSHNAME AS UserName,
       SUBSTRING(ZJID, 1, 12) AS PhoneNumber,
       (SELECT COUNT(*) FROM ZWAMESSAGE
         WHERE ZWACHATSESSION.ZSESSIONTYPE == 0
           AND ZMESSAGETYPE IN ('0','1','2','3','4','5','7','8','11','14','15','38','39')
           AND (ZFROMJID = ZWAPROFILEPUSHNAME.ZJID OR ZTOJID = ZWAPROFILEPUSHNAME.ZJID)
       ) AS NumberOfMessages,
       datetime(ZWAMESSAGE.ZMESSAGEDATE + 978307200, 'unixepoch') AS MessageDate
FROM ZWACHATSESSION
LEFT JOIN ZWAMESSAGE ON ZWACHATSESSION.ZLASTMESSAGE = ZWAMESSAGE.Z_PK
LEFT JOIN ZWAPROFILEPUSHNAME ON ZWACHATSESSION.ZCONTACTJID = ZWAPROFILEPUSHNAME.ZJID
WHERE ZWACHATSESSION.ZSESSIONTYPE == 0 AND ZJID IS NOT NULL
GROUP BY ZWACHATSESSION.ZPARTNERNAME
HAVING MAX(datetime(ZWAMESSAGE.ZMESSAGEDATE + 978307200, 'unixepoch')) AND NumberOfMessages > 0
ORDER BY CASE WHEN ZWACHATSESSION.ZPARTNERNAME LIKE '+%' THEN 1 ELSE 0 END ASC,
         ZWACHATSESSION.ZPARTNERNAME
"""

PRIVATE_CHAT_COUNTERS = """
SELECT count(case when True then 1 else null end) as TotalMessages,
       count(case when ZWAMESSAGE.ZMESSAGETYPE = 14 then 1 else null end) as DeletedMessages,
       count(case when ZWAMESSAGE.ZMESSAGETYPE IN ('1','38','2','39','3','4','5','7','8') then 1 else null end) as Attachments,
       count(case when ZWAMESSAGE.ZMESSAGETYPE IN (1, 38) then 1 else null end) as Images,
       count(case when ZWAMESSAGE.ZMESSAGETYPE IN (2, 39) then 1 else null end) as Videos,
       count(case when ZWAMESSAGE.ZMESSAGETYPE = 3 then 1 else null end) as Audio,
       count(case when ZWAMESSAGE.ZMESSAGETYPE = 4 then 1 else null end) as Contacts,
       count(case when ZWAMESSAGE.ZMESSAGETYPE = 5 then 1 else null end) as Positions,
       count(case when ZWAMESSAGE.ZMESSAGETYPE = 15 then 1 else null end) as Stickers,
       count(case when ZWAMESSAGE.ZMESSAGETYPE = 7 then 1 else null end) as Url,
       count(case when ZWAMESSAGE.ZMESSAGETYPE = 8 then 1 else null end) as File
FROM (ZWAMESSAGE JOIN ZWACHATSESSION ON ZWAMESSAGE.ZCHATSESSION = ZWACHATSESSION.Z_PK)
LEFT JOIN ZWAMEDIAITEM ON ZWAMESSAGE.ZMEDIAITEM = ZWAMEDIAITEM.Z_PK
WHERE ZWACHATSESSION.ZCONTACTJID LIKE :jid_pattern AND ZSESSIONTYPE = 0
"""

PRIVATE_CHAT_MESSAGES = """
SELECT SUBSTRING(ZFROMJID, 1, 12) as user,
       ZWAMESSAGE.ZTEXT as text,
       ZWACHATSESSION.ZPARTNERNAME as ZPARTNERNAME,
       ZWAMESSAGE.ZMESSAGETYPE as ZMESSAGETYPE,
       ZWAMESSAGEINFO.ZRECEIPTINFO as dateTimeInfos,
       datetime(ZWAMESSAGE.ZMESSAGEDATE + 978307200, 'unixepoch') as receiveDateTime,
       ZMOVIEDURATION as duration,
       ZLATITUDE as latitude,
       ZLONGITUDE as longitude,
       ZVCARDNAME as contactName,
       ZVCARDSTRING as vcardString,
       SUBSTR(ZWAMEDIAITEM.ZVCARDSTRING, INSTR(ZWAMEDIAITEM.ZVCARDSTRING, '/') + 1) as fileExtension,
       coalesce(ZWAMEDIAITEM.ZMEDIALOCALPATH, '') AS mediaPath
FROM (ZWAMESSAGE JOIN ZWACHATSESSION ON ZWAMESSAGE.ZCHATSESSION = ZWACHATSESSION.Z_PK)
LEFT JOIN ZWAMEDIAITEM ON ZWAMESSAGE.ZMEDIAITEM = ZWAMEDIAITEM.Z_PK
LEFT JOIN ZWAMESSAGEINFO ON ZWAMESSAGEINFO.ZMESSAGE = ZWAMESSAGE.Z_PK
WHERE ZWACHATSESSION.ZCONTACTJID LIKE :jid_pattern
  AND ZWACHATSESSION.ZGROUPINFO is null
  AND ZMESSAGETYPE IN ('0','1','2','3','4','5','7','8','11','14','15','38','39')
ORDER BY ZWAMESSAGE.ZSENTDATE ASC
"""

GPS_LOCATIONS = """
SELECT CASE WHEN ZWAMESSAGE.ZGROUPMEMBER IS NOT NULL THEN SUBSTRING(ZWAGROUPMEMBER.ZMEMBERJID, 1, 12)
            WHEN ZWAMESSAGE.ZFROMJID IS NULL THEN 'Database owner'
            ELSE SUBSTRING(ZWAMESSAGE.ZFROMJID, 1, 12) END AS Sender,
       CASE WHEN ZWAMESSAGE.ZTOJID IS NULL AND ZWAMESSAGE.ZGROUPMEMBER IS NULL THEN 'Database owner'
            WHEN ZWAMESSAGE.ZTOJID IS NULL AND ZWAMESSAGE.ZGROUPMEMBER IS NOT NULL THEN ZWACHATSESSION.ZPARTNERNAME
            ELSE SUBSTRING(ZWAMESSAGE.ZTOJID, 1, 12) END AS Receiver,
       datetime(ZWAMESSAGE.ZMESSAGEDATE + 978307200, 'unixepoch') AS MessageDate,
       ZLATITUDE AS Latitude,
       ZLONGITUDE AS Longitude
FROM ZWAMESSAGE
JOIN ZWACHATSESSION ON ZWACHATSESSION.Z_PK = ZWAMESSAGE.ZCHATSESSION
LEFT JOIN ZWAMEDIAITEM ON ZWAMESSAGE.ZMEDIAITEM = ZWAMEDIAITEM.Z_PK
LEFT JOIN ZWAGROUPMEMBER ON ZWAMESSAGE.ZGROUPMEMBER = ZWAGROUPMEMBER.Z_PK
WHERE ZWAMESSAGE.ZMESSAGETYPE = 5
ORDER BY MessageDate
"""

BLOCKED_CONTACTS = """
SELECT CASE WHEN ZPUSHNAME IS NULL THEN 'Name not available' ELSE ZPUSHNAME END AS Name,
       SUBSTRING(ZWABLACKLISTITEM.ZJID, 1, 12) AS PhoneNumber
FROM ZWABLACKLISTITEM
LEFT JOIN ZWAPROFILEPUSHNAME ON ZWABLACKLISTITEM.ZJID = ZWAPROFILEPUSHNAME.ZJID
"""

GROUP_LIST = """
SELECT ZPARTNERNAME AS Group_Name,
       datetime(ZWAMESSAGE.ZMESSAGEDATE + 978307200, 'unixepoch') AS Message_Date,
       (SELECT COUNT(*) FROM ZWAMESSAGE
         WHERE ZWAMESSAGE.ZMESSAGETYPE IN ('0','1','38','2','39','3','4','5','7','8','11','14','15','46')
           AND (ZWAMESSAGE.ZTOJID = ZWACHATSESSION.ZCONTACTJID OR ZWAMESSAGE.ZFROMJID = ZWACHATSESSION.ZCONTACTJID)
       ) AS Number_of_Messages,
       ZWACHATPUSHCONFIG.ZMUTEDUNTIL AS Is_muted
FROM ZWAMESSAGE
LEFT JOIN ZWACHATSESSION ON ZWACHATSESSION.ZLASTMESSAGE = ZWAMESSAGE.Z_PK
LEFT JOIN ZWAPROFILEPUSHNAME ON ZWACHATSESSION.ZCONTACTJID = ZWAPROFILEPUSHNAME.ZJID
LEFT JOIN ZWACHATPUSHCONFIG ON ZWACHATPUSHCONFIG.ZJID = ZWACHATSESSION.ZCONTACTJID
WHERE ZSESSIONTYPE = 1
ORDER BY ZWACHATSESSION.ZPARTNERNAME ASC
"""

GROUP_CHAT_COUNTERS = """
SELECT count(case when ZWAMESSAGE.ZMESSAGETYPE IN ('0','1','38','2','39','3','4','5','7','8','11','14','15','46') then 1 else null end) as totalMessages,
       count(case when ZWAMESSAGE.ZMESSAGETYPE = 14 then 1 else null end) as deletedMessages,
       count(case when ZWAMESSAGE.ZMESSAGETYPE IN ('1','38','2','39','3','4','5','7','8') then 1 else null end) as attachments,
       count(case when ZWAMESSAGE.ZMESSAGETYPE IN (1, 38) then 1 else null end) as images,
       count(case when ZWAMESSAGE.ZMESSAGETYPE IN (2, 39) then 1 else null end) as videos,
       count(case when ZWAMESSAGE.ZMESSAGETYPE = 3 then 1 else null end) as audio,
       count(case when ZWAMESSAGE.ZMESSAGETYPE = 4 then 1 else null end) as contacts,
       count(case when ZWAMESSAGE.ZMESSAGETYPE = 5 then 1 else null end) as positions,
       count(case when ZWAMESSAGE.ZMESSAGETYPE = 15 then 1 else null end) as stickers,
       count(case when ZWAMESSAGE.ZMESSAGETYPE = 7 then 1 else null end) as url,
       count(case when ZWAMESSAGE.ZMESSAGETYPE = 8 then 1 else null end) as file
FROM ZWAMESSAGE
JOIN ZWACHATSESSION ON ZWACHATSESSION.Z_PK = ZWAMESSAGE.ZCHATSESSION
LEFT JOIN ZWAMEDIAITEM ON ZWAMESSAGE.ZMEDIAITEM = ZWAMEDIAITEM.Z_PK
LEFT JOIN ZWAGROUPMEMBER ON ZWAMESSAGE.ZGROUPMEMBER = ZWAGROUPMEMBER.Z_PK
WHERE ZWACHATSESSION.ZPARTNERNAME LIKE :group_pattern
"""

GROUP_CHAT_MESSAGES = """
SELECT SUBSTRING(ZWAGROUPMEMBER.ZMEMBERJID, 1, 12) as user,
       CASE WHEN (SELECT CASE WHEN ZWACHATSESSION.ZPARTNERNAME IS NOT NULL THEN ZWACHATSESSION.ZPARTNERNAME
                              ELSE ZWAPROFILEPUSHNAME.ZPUSHNAME END
                  FROM ZWACHATSESSION
                  LEFT JOIN ZWAPROFILEPUSHNAME ON ZWACHATSESSION.ZCONTACTJID = ZWAPROFILEPUSHNAME.ZJID
                  WHERE ZJID LIKE ZWAGROUPMEMBER.ZMEMBERJID) IS NOT NULL
            THEN (SELECT CASE WHEN ZWACHATSESSION.ZPARTNERNAME IS NOT NULL THEN ZWACHATSESSION.ZPARTNERNAME
                              ELSE ZWAPROFILEPUSHNAME.ZPUSHNAME END
                  FROM ZWACHATSESSION
                  LEFT JOIN ZWAPROFILEPUSHNAME ON ZWACHATSESSION.ZCONTACTJID = ZWAPROFILEPUSHNAME.ZJID
                  WHERE ZJID LIKE ZWAGROUPMEMBER.ZMEMBERJID)
            WHEN ZWAGROUPMEMBER.ZMEMBERJID IS NULL THEN NULL
            ELSE 'Name not available' END AS contactName,
       ZWAMESSAGE.ZTEXT AS text,
       ZWAMESSAGE.ZMESSAGETYPE AS ZMESSAGETYPE,
       ZWAMESSAGEINFO.ZRECEIPTINFO as dateTimeInfos,
       datetime(ZWAMESSAGE.ZMESSAGEDATE + 978307200, 'unixepoch') AS receiveDateTime,
       ZMOVIEDURATION AS duration,
       ZLATITUDE AS latitude,
       ZLONGITUDE AS longitude,
       ZVCARDNAME AS vcardContactName,
       ZVCARDSTRING AS vcardString,
       SUBSTR(ZWAMEDIAITEM.ZVCARDSTRING, INSTR(ZWAMEDIAITEM.ZVCARDSTRING, '/') + 1) AS fileExtension,
       coalesce(ZWAMEDIAITEM.ZMEDIALOCALPATH, '') AS mediaPath
FROM ZWAMESSAGE
JOIN ZWACHATSESSION ON ZWACHATSESSION.Z_PK = ZWAMESSAGE.ZCHATSESSION
LEFT JOIN ZWAMEDIAITEM ON ZWAMESSAGE.ZMEDIAITEM = ZWAMEDIAITEM.Z_PK
LEFT JOIN ZWAGROUPMEMBER ON ZWAMESSAGE.ZGROUPMEMBER = ZWAGROUPMEMBER.Z_PK
LEFT JOIN ZWAMESSAGEINFO ON ZWAMESSAGEINFO.ZMESSAGE = ZWAMESSAGE.Z_PK
WHERE ZWACHATSESSION.ZPARTNERNAME LIKE :group_pattern
  AND ZMESSAGETYPE IN ('0','1','2','3','4','5','7','8','11','14','15','38','39')
ORDER BY ZWAMESSAGE.ZSENTDATE ASC
"""

MANIFEST_CHAT_MEDIA = """
SELECT fileID, relativePath, flags
FROM Files
WHERE domain = :domain AND relativePath LIKE :path_pattern
ORDER BY relativePath
"""

MANIFEST_PROFILE_PIC = """
SELECT fileID, relativePath, flags
FROM Files
WHERE domain = :domain
  AND relativePath LIKE :path_pattern
  AND relativePath NOT LIKE '%-%-%'
ORDER BY relativePath DESC
"""
